### ISSUE TITLE
add support to send direct commands using VISADevice.write("") from virtual channel

### ISSUE THREAD

**Issue by schroeca** [OE-FET/JISA#12]
**Is your feature request related to a problem? Please describe.**
I am using multi-channel devices and currently, there is no way to send a direct command to a VISADevice from a channel object.

**Describe the solution you'd like**
I would like to cast or extract the base device from a channel object.

**Describe alternatives you've considered**
I could always use the multichannel device without extracting the channels but this might introduce other errors. Wrong channel index while copy-pasting code.

**Comment by WuhrlWuhrd** [comment]
Hello Andreas,

Perhaps quite relevantly, I've recently been reworking the sub/virtual instrument structure. Specifically, making sure multi-channel instruments act as collections of their channels, rather than generating virtual channels on the fly that call back to the multi-channel object --- thus allowing sub-instruments to be represented by their own classes, rather than just standard implementations of their base interfaces.

Therefore, an object representing a sub-instrument/channel can now provide more methods than just those required by their instrument interface. For instance, the dual-channel TSP-based Keithley SMUs (i.e., `K26XXX`) now have channels represented as `KSMU` objects which can be accessed directly as `xxx.SMU_A`, and `xxx.SMU_B`, which means we can add extra methods to the `KSMU` class that are Keithley-TSP-specific.

Part of this revamp has introduced the `SubInstrument` interface that is used to identify sub-instrument classes to JISA, so that they don't show up in certain user-interface elements. If needed, I can add a `xxx.getParentInstrument()` method to this interface... However, to be in-keeping with the JISA way of doing things, I would recommend instead implementing methods for whatever commands you're sending directly to your instruments in the class for the sub-instruments. The whole point of the project is to avoid sending raw commands using `write(...)` etc in your control/measurement routines.

I hope that helps.

All the best,
Will.

**Comment by schroeca** [comment]
Hi,

I completely agree with you if it comes to the ideal way of working.

Implementing the commands directly in the device class would be the preferred way but in our organisation we have a lot of operators that are capable of reading the programing manual to find the proper commands to get the job done.

These colleagues are not the best SW developers and my experience showed that it is beneficial if they implement the test sequences using direct commands and request an implementation after the first debugging.

We tried to get them to implement the commands by them self, but the resulting implementation caused more issues than it could solve.

I would be very helpful to have this generic getParentInstrument() method.

In case you don't want to have this piece of code in your implementation, we will add it by ourselves.

Thx

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by WuhrlWuhrd** [comment]
I completely forgot to mention, but the aforementioned `getParentInstrument()` method was defined in the `SubInstrument` interface (https://github.com/OE-FET/JISA/blob/master/src/jisa/devices/interfaces/SubInstrument.java) and implemented in all relevant instruments ages ago now, so this should be possible, and I should probably close this.

**Comment by schroeca** [comment]
Thx for the update.

BR


Andreas Schröck
Principal System Engineer / Senior Manager A&C/CONN/NFC
Renesas Electronics
t: +43 316 269 259

________________________________
