### ISSUE TITLE
Is it a bug with the class: SerialAddress?

### ISSUE THREAD

**Issue by uoiah** [OE-FET/JISA#2]
Hi, 
There are two questions below:
Firstly:
I find the method toString() of this class:
`
    public String toString() {
        return String.format("ASRL::%s::INSTR", port);
    }
`
if the port is "8", then it returns "ASRL::8::INSTR", but in my application, it should be "ASRL8::INSTR". Does it has something wrong?
Secondly:
I made some changes in this class ,so as to let it returns just like what I want. but it lead to a Exception which gives tips below:
    SerialDriver: can only open native serial connections with the native serial driver!

**Comment by WuhrlWuhrd** [comment]
`SerialAddress` recently underwent some changes that I am yet to document. In short, it now requires the full port name not just the number. So in your case (assuming you're on Windows) it would be `SerialAddress("COM8")`.

The reason for this is that serial port names follow a very different convention on UNIX-like system (such as Mac and Linux) where a simple numbering system no-longer suffices and means the VISA standard of `ASRL<n>::INSTR` just straight-up doesn't work.

Basically, for example, on Linux you can have two serial ports labelled as "port 8" if one is a regular serial port and the other is a USB adaptor: `/dev/ttyS8` and `/dev/ttyUSB8` and because of this VISA gives up and forces you to pre-configure which port should have what number in VISA. By using this new address format JISA can instead pass the full port name to the native serial driver and get round that whole mess completely.

On Windows, the VISA driver automatically figures out what the equivalent VISA address is and translates as necessary. The native serial driver just uses the new format as it is. In short, it isn't bugged and it should work fine as it is on the repo so long as you supply it with the full port name (ie "COM8" in your case).

**Comment by WuhrlWuhrd** [comment]
The VISA driver automatically figures out what the equivalent VISA address is and translates as necessary. The native serial driver just uses the new format as it is.

**Comment by uoiah** [comment]
Hi William,
I put "COM8" in SerialAddress's constructor, just like you said. It works well now,  I use the program controlling a FCL200 stage's movement, velocity, and acceleration successfully.
Your Jisa is a great project!
Thank you very much!

Best Regard,
Yf W
