### ISSUE TITLE
using jdk 1.8 causes compiler error.

### ISSUE THREAD

**Issue by schroeca** [OE-FET/JISA#3]
**Describe the bug**
The library can not be used with jdk 1.8 as mentioned in the documentation. Is it necessary to use jdk 11 or is there a way to use jdk 1.8?

**Comment by WuhrlWuhrd** [comment]
Hello! Yes, my apologies, the documentation that says that is out of date,
I thought I had updated all instances of that but apparently not. Could you
tell me where it says that, so I can correct it.

I shifted to Java 11 since Java 8 was no-longer receiving public updates.
It should still be possible to compile the library using Java 8 with some
minor modifications though, so if you really require a Java 8 version I
could see if I can get you a compiled jar file?

Edit: I think I've found the page and updated it now.

**Comment by WuhrlWuhrd** [comment]
In fact, I just got it to do it. It seems to work, haven't tested everything with it though.

[https://github.com/OE-FET/JISA/raw/master/JISA-1.8.jar](https://github.com/OE-FET/JISA/raw/master/JISA-1.8.jar)
