### ISSUE TITLE
Master not working in Intellij 2021

### ISSUE THREAD

**Issue by schroeca** [OE-FET/JISA#4]
I have downloaded the latest master and wanted to test the GUI features. But I could not start the main. Within Intellij it generates an "Toolkit not initialized" exception.

I am using openjdk 11 + javafx SDK (Which should not be necessary) on Windows 10 64bit.

Have you ever seen this behaviour? Any idea how to fix this?

**Update:**

It is working now but I had to add some wait time before and after calling "JavaFX.launch();"

**Comment by WuhrlWuhrd** [comment]
Ah glad you fixed!

I remember noticing this happen once when using - I think - the "Azure Zulu" Java + JFX SDK (i.e. [this one](https://www.azul.com/downloads/?version=java-11-lts&package=jdk-fx)). My solution at the time was to switch to just a plain Java 11 SDK/runtime and subsequently forgot about it.

I'm not sure if it was specific to that provider or perhaps all builds that include JavaFX? That's certainly interesting about the wait solution, it seems to suggest that something is loaded in a different order/timing on such affected SDKs - I'll implement that in the main build so that others hopefully don't run into this issue too.

Thanks for looking into this!

(Also sorry for the late response - I'm buried with writing my thesis right now)
